PIN_ROOT ?= /home/john/Adv_Comp_Arch/pin-external-3.31-98869-gfa6f126a8-gcc-linux

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
